Solution1/StarBazar.Web/ViewModels/CategoryViewModel.cs
using StarBazar.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StarBazar.Web.ViewModels
{
    public class CategorySearchViewModel
    {
        public List<Category> Categories { get; set; }
        public string SearchTerm { get; set; }

      //  public Pager Pager { get; set; }
    }

    public class NewCategoryViewModel
    {
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }

        [MaxLength(500)]
        public string Description { get; set; }

        public string ImageURL { get; set; }

        public bool isFeatured { get; set; }
    }

    public class EditCategoryViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }

        public string ImageURL { get; set; }

        public bool isFeatured { get; set; }
    }
}

Solution1/StarBazar.Web/Controllers/CategoryController.cs
using StarBazar.Entities;
using StarBazar.Services;
using StarBazar.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StarBazar.Web.Controllers
{
    public class CategoryController : Controller
    {
        CategoryService categoryService = new CategoryService();
        // GET: Category

        public ActionResult CategoryTable(string search)
        {
            var categories = categoryService.GetCategories();
            if (string.IsNullOrEmpty(search) == false)
            {
                categories = categories.Where(p => p.Name != null && p.Name.ToLower().Contains(search.ToLower())).ToList();
            }
            return PartialView(categories);
        }

        public ActionResult Index()
        {
            var categoryList = categoryService.GetCategories();
            return View(categoryList);
        }
        public ActionResult Create()
        {
            var categoryList = categoryService.GetCategories();
            return PartialView(categoryList);
        }

        [HttpPost]
        public ActionResult Create(NewCategoryViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var newCategory = new Category();
                newCategory.Name = vm.Name;
                newCategory.Description = vm.Description;
                newCategory.ImageURL = vm.ImageURL;
                newCategory.isFeatured = vm.isFeatured;

                categoryService.SaveCategory(newCategory);

                return RedirectToAction("CategoryTable");
            }
            else
            {
                return new HttpStatusCodeResult(500);
            }
        }

        public ActionResult Edit(int id)
        {
            EditCategoryViewModel model = new EditCategoryViewModel();

            var category = categoryService.GetCategoryById(id);

            model.Id = category.Id;
            model.Name = category.Name;
            model.Description = category.Description;
            model.ImageURL = category.ImageURL;
            model.isFeatured = category.isFeatured;
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(EditCategoryViewModel vm)
        {
            var existingCategory = categoryService.GetCategoryById(vm.Id);
            existingCategory.Name = vm.Name;
            existingCategory.Description = vm.Description;
            existingCategory.ImageURL = vm.ImageURL;
            existingCategory.isFeatured = vm.isFeatured;

            categoryService.UpdateCategory(existingCategory);

            return RedirectToAction("CategoryTable");
        }


        [HttpPost]
        public ActionResult Delete(int Id)
        {
            categoryService.DeleteCategory(Id);
            return RedirectToAction("CategoryTable");
        }
        
    }
}

Solution1/StarBazar.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StarBazar.Web.Controllers
{
    public class SharedController : Controller
    {
        // GET: Shared
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/Content/images/"), fileName);

                file.SaveAs(path);

                result.Data = new { Success = true, ImageURL = string.Format("/content/images/{0}", fileName) };

                //var newImage = new Image() { Name = fileName };

                //if (ImagesService.Instance.SaveNewImage(newImage))
                //{
                //    result.Data = new { Success = true, Image = fileName, File = newImage.ID, ImageURL = string.Format("{0}{1}", Variables.ImageFolderPath, fileName) };
                //}
                //else
                //{
                //    result.Data = new { success = false, Message = new HttpStatusCodeResult(500) };
                //}
            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }

            return result;
        }
    }
}

Solution1/StarBazar.Web/Views/Category/CategoryTable.cshtml
@model List<Category>
@{
    ViewBag.Title = "CategoryTable";
}


<form method="post" href="@Url.Action("CategoryTable", "Category")">
    <label>Search</label>
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <input id="idSearch" class="form-control" type="search" />
            </div>
        </div>
        <div class="col-md-4">
            <button type="button" id="btnSearch">Search</button>
            <button id="idNew" type="button">New</button>
        </div>
    </div>

</form>
<h2>CategoryTable</h2>

<div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Category Name</th>
                <th>Description</th>
                <th class="font-weight-bold">Products</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Description</td>
                    <td>
                        <button class="btnEdit" data-id="@item.Id">Edit</button>
                        <button class="btnDelete" data-id="@item.Id">Delete</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    $("#btnSearch").click(function () {
        var search = $("#idSearch").val();
        $.ajax({
            url:'@Url.Action("CategoryTable", "Category")',
            data: {
                search: search
            }

        })
            .done(function (data) {
                $('#EditTableContainer').html(data)
                $('#actionEditContainer').html('')
            })

            .fail(function (xmlHttpRequest, textStatus) {
                alert('Fail');
            });

    });

    $("#idNew").click(function () {
        $.ajax({
            url: '@Url.Action("Create", "Category")',
        })
            .done(function (data) {
                $('#actionEditContainer').html(data)
                focusAction("actionEditContainer");
            })

            .fail(function (xmlHttpRequest, textStatus) {
                alert('Fail');
            });

    });

    $(".btnEdit").click(function () {
        $.ajax({
            url: '@Url.Action("Edit", "Category")',
            data: {
                Id: $(this).attr('data-id')
            }
        })
            .done(function (data) {
                $('#actionEditContainer').html(data)
                focusAction("actionEditContainer");

            })
            .fail(function (xmlHttpRequest, textStatus) {
                alert('Fail');
            });

    });

    $(".btnDelete").click(function () {

        swal({
            title: "Confirmed?",
            text: "Are you sure want to delete this product?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("Delete", "Category")',
                        data: {
                            Id: $(this).attr('data-id')
                        }
                    })
                        .done(function (data) {
                            $('#EditTableContainer').html(data)
                        })

                        .fail(function (xmlHttpRequest, textStatus) {
                            alert('Fail');
                        });
                    swal("Record deleted succesfully", {
                        icon: "success",
                    });
                }
            });

    });



</script>

Solution1/StarBazar.Web/Views/Category/Create.cshtml
@{
    ViewBag.Title = "Create";
    var imageURL = "/Content/images/placeholder-image.png";
}

<h2>Create</h2>
<form id="createContainer">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Name <span class="text-danger">*</span></label>
                <input class="form-control" name="Name" />
            </div>
            <div class="form-group">
                <label>Description</label>
                <input class="form-control" name="Description" />
            </div>
            <div class="form-group">
                <label>Image</label>
                <input type="hidden" id="ImageURL" name="ImageURL" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
            </div>
            <div class="form-group">
                <label>Is Featured?</label>
                <div class="input-group">
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="True" /> True</label>
                    </div>
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="False" /> False</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img class="img-thumbnail img-fluid" id="categoryImage" src="@imageURL" />
            </div>
        </div>
    </div>

    <button id="btnSave" type="button" class="btn btn-danger">Save</button>
    <button id="cancelBtn" type="button" class="btn btn-danger">Cancel</button>
</form>

<script>
    $("#btnSave").click(function () {
        debugger;
        if ($("#createContainer").valid()) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("Create", "Category")',
                data: $('#createContainer').serialize()
            })
                .done(function (data) {
                    $('#EditTableContainer').html(data);
                    $('#actionEditContainer').html('');
                })

                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    swal({
                        title: "Warning?",
                        text: "Please Enter All Required Fields",
                        icon: "warning",
                        buttons: true,
                        dangerMode: true,
                    })
                });
        }
        else {
            swal({
                title: "Warning?",
                text: "Please Enter All Required Fields",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
        }

    });

    $("#cancelBtn").click(function () {
        $("#createContainer").html("");

        focusAction("EditTableContainer");
    });

    $("#imageUpload").change(function () {
        var element = this;

        var formData = new FormData();

        var totalFiles = element.files.length;

        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
            .done(function (reposne) {
                console.log(reposne);


                if (reposne.Success) {
                    $("#ImageURL").val(reposne.ImageURL);
                    $("#categoryImage").attr("src", reposne.ImageURL);
        }
    })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert('Fail');
        });
    });

    $('#createContainer').validate({
        rules: {
            Name: {
                required: true,
                maxlength: 50,
            },
            Description: {
                maxlength: 500
            }
        },
        messages: {
            Name: {
                required: 'Name is required',
                maxlength: 'Maximum Length is 50'
            },
            Description: {
                maxlength: 'Maximum Length is 500'
            }
        }
    });
</script>

Solution1/StarBazar.Web/Views/Category/Delete.cshtml
@model StarBazar.Entities.Category
@{
    ViewBag.Title = "Delete";
}

<h2>Are you sure wants to delete this category</h2>
<form method="post">
    <input type="hidden" name="Id" value="@Model.Id" />
    <button type="submit">Delete</button>
</form>
<a href="/Index">Cancel</a>

Solution1/StarBazar.Web/Views/Category/Edit.cshtml
@model StarBazar.Web.ViewModels.EditCategoryViewModel
@{
    ViewBag.Title = "Edit";
    var trueChecked = Model.isFeatured ? "checked" : string.Empty;
    var falseChecked = !Model.isFeatured ? "checked" : string.Empty;

    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/images/placeholder-image.png";

}
<head>
    @Scripts.Render("~/bundles/jquery")
</head>


<form id="editContainer">
    <input type="hidden" name="Id" value="@Model.Id" />
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Name</label>
                    <input class="form-control" name="Name" value="@Model.Name" />
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <input class="form-control" name="Description" value="@Model.Description" />
                </div>
                <div class="form-group">
                    <label>Image</label>
                    <input type="hidden" id="ImageURL" name="ImageURL" value="@Model.ImageURL" />
                    <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
                </div>
                <div class="form-group">
                    <label>Is Featured?</label>
                    <div class="input-group">
                        <div class="radio form-control">
                            <label><input name="isFeatured" type="radio" value="True" @trueChecked /> True</label>
                        </div>
                        <div class="radio form-control">
                            <label><input name="isFeatured" type="radio" value="False" @falseChecked /> False</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="thumb">
                    <img src="@imageURL" class="img-thumbnail img-fluid" id="categoryImage" />
                </div>
            </div>
        </div>
        <button id="btnEditSave" type="button">Update</button>
    </div>
</form>

<script>
    $("#btnEditSave").click(function () {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Edit", "Category")',
            data: $('#editContainer').serialize()
        })
            .done(function (data) {
                $('#EditTableContainer').html(data);
                $('#actionEditContainer').html('');
                focusAction("EditTableContainer");
            })

            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert('Fail');
            });

    });

    $("#imageUpload").change(function () {
        var element = this;

        var formData = new FormData();

        var totalFiles = element.files.length;

        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
            .done(function (reposne) {
                console.log(reposne);


                if (reposne.Success) {
                    $("#ImageURL").val(reposne.ImageURL);
                    $("#categoryImage").attr("src", reposne.ImageURL);
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert('Fail');
            });
    });

</script>

Solution1/StarBazar.Web/Views/Category/Index.cshtml
@model List<StarBazar.Entities.Category>
@{
    ViewBag.Title = "Index";
}


<div class="container">
    <div id="EditTableContainer">
        @{
            Html.RenderAction("CategoryTable");

            //Html.RenderAction("Create");
        }
    </div>

    <hr />
    <div id="actionEditContainer">

    </div>

</div>

<script>
	function focusAction(controlToFocus) {
		$('html, body').animate({
			scrollTop: $("#" + controlToFocus).offset().top - 100
		}, 1000);
	}
</script>