Solution1/StarBazar.Web/ViewModels/ProductViewModel.cs
using StarBazar.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StarBazar.Web.ViewModels
{
    public class ProductSearchViewModel
    {
        public int PageNo { get; set; }
        public List<Product> Products { get; set; }
        public string SearchTerm { get; set; }

        // public Pager Pager { get; set; }
    }
    public class NewProductViewModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public string ImageURL { get; set; }

        public List<Category> AvailableCategories { get; set; }
    }

    public class EditProductViewModel
    {
        public int ID { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public string ImageURL { get; set; }

        public List<Category> AvailableCategories { get; set; }
    }


    public class ProductViewModel
    {
        public Product Product { get; set; }
    }
}

Solution1/StarBazar.Web/Controllers/ProductController.cs
using StarBazar.Entities;
using StarBazar.Services;
using StarBazar.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StarBazar.Web.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductTable(string search, int? pageNo)
        {
            ProductSearchViewModel model = new ProductSearchViewModel();
            model.SearchTerm = search;

           model.PageNo= pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;

            var totalRecords = ProductService.Instance.GetProductsCount(search);
            model.Products = ProductService.Instance.GetProducts(model.PageNo);

            //model.Pager = new Pager(totalRecords, pageNo, pageSize);

            return PartialView(model);
        }
        #region Creation
        public ActionResult Create()
        {
            CategoryService categoryService = new CategoryService();
            NewProductViewModel model = new NewProductViewModel();

            model.AvailableCategories = categoryService.GetCategories();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Create(NewProductViewModel vm)
        {
            CategoryService categoryService = new CategoryService();
            var newProduct = new Product();
            newProduct.Name = vm.Name;
            newProduct.Description = vm.Description;
            newProduct.Price = vm.Price;
            newProduct.Category = categoryService.GetCategoryById(vm.CategoryID);
            newProduct.ImageURL = vm.ImageURL;

            ProductService.Instance.SaveProduct(newProduct);
            return RedirectToAction("ProductTable");
        }
        #endregion

        #region Updation

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            CategoryService categoryService = new CategoryService();
            EditProductViewModel vm = new EditProductViewModel();

            var product = ProductService.Instance.GetProductById(Id);

            vm.ID = product.Id;
            vm.Name = product.Name;
            vm.Description = product.Description;
            vm.Price = product.Price;
            vm.CategoryID = product.Category != null ? product.Category.Id : 0;
            vm.ImageURL = product.ImageURL;

            vm.AvailableCategories = categoryService.GetCategories();

            return PartialView(vm);
        }

        [HttpPost]
        public ActionResult Edit(EditProductViewModel model)
        {
            var existingProduct = ProductService.Instance.GetProductById(model.ID);
            existingProduct.Name = model.Name;
            existingProduct.Description = model.Description;
            existingProduct.Price = model.Price;

            existingProduct.Category = null; //mark it null. Because the referncy key is changed below
            existingProduct.CategoryId = model.CategoryID;

            //dont update imageURL if its empty
            if (!string.IsNullOrEmpty(model.ImageURL))
            {
                existingProduct.ImageURL = model.ImageURL;
            }

            ProductService.Instance.UpdateProduct(existingProduct);

            return RedirectToAction("ProductTable");
        }

        #endregion
        [HttpPost]
        public ActionResult Delete(int Id)
        {
            ProductService.Instance.DeleteProduct(Id);
            return RedirectToAction("ProductTable");
        }

        [HttpGet]
        public ActionResult Details(int Id)
        {
            ProductViewModel vm = new ProductViewModel();
            vm.Product = ProductService.Instance.GetProductById(Id);

            return View(vm);
        }

    }
}

Solution1/StarBazar.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StarBazar.Web.Controllers
{
    public class SharedController : Controller
    {
        // GET: Shared
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/Content/images/"), fileName);

                file.SaveAs(path);

                result.Data = new { Success = true, ImageURL = string.Format("/content/images/{0}", fileName) };

                //var newImage = new Image() { Name = fileName };

                //if (ImagesService.Instance.SaveNewImage(newImage))
                //{
                //    result.Data = new { Success = true, Image = fileName, File = newImage.ID, ImageURL = string.Format("{0}{1}", Variables.ImageFolderPath, fileName) };
                //}
                //else
                //{
                //    result.Data = new { success = false, Message = new HttpStatusCodeResult(500) };
                //}
            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }

            return result;
        }
    }
}

Solution1/StarBazar.Web/Controllers/WidgetController.cs
using StarBazar.Services;
using StarBazar.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StarBazar.Web.Controllers
{
    public class WidgetController : Controller
    {
        // GET: Widget
        public ActionResult Products(bool isLatestProducts ,int? categoryId=0)
        {
            ProductWidgetViewModel vm = new ProductWidgetViewModel();

            if (isLatestProducts)
            {
                vm.Products = ProductService.Instance.GetLatestProducts(4);
            }
            else if (categoryId.HasValue && categoryId.Value > 0)
            {
                vm.Products = ProductService.Instance.GetProductsByCategory(categoryId.Value, 4);
            }
            else
            {
                vm.Products = ProductService.Instance.GetWidgetProducts(1,8);
            }

            return PartialView(vm);
        }
    }
}

Solution1/StarBazar.Web/Views/Product/Create.cshtml
@model StarBazar.Web.ViewModels.NewProductViewModel
@{
    ViewBag.Title = "Create";
    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/images/placeholder-image.png";
}

<h2>Create Product</h2>

<form id="createContainer">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Category</label>
                <select class="form-control" name="CategoryID">
                    @foreach (var category in Model.AvailableCategories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" name="Name" />
            </div>
            <div class="form-group">
                <label>Description</label>
                <input class="form-control" name="Description" />
            </div>
            <div class="form-group">
                <label>Price</label>
                <input class="form-control" name="Price" />
            </div>
            <div class="form-group">
                <label>Image</label>
                <input type="hidden" id="ImageURL" name="ImageURL" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
            </div>
            <button id="btnSave" type="button" class="btn btn-primary">Save</button>
            <button id="btnCancel" type="button" class="btn btn-primary">Cancel</button>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img class="img-thumbnail img-fluid" id="productImage" src="@imageURL" />
            </div>
        </div>
    </div>	
</form>



<script>
    $("#btnSave").click(function () {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Create", "Product")',
            data: $('#createContainer').serialize()
        })
            .done(function (data) {
                $('#tableContainer').html(data);
                $('#actionContainer').html('');
            })

            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert('Fail');
            });

    });

    $("#imageUpload").change(function () {
        var element = this;

        var formData = new FormData();

        var totalFiles = element.files.length;

        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
            .done(function (reposne) {
                console.log(reposne);


                if (reposne.Success) {
                    $("#ImageURL").val(reposne.ImageURL);
                    $("#productImage").attr("src", reposne.ImageURL);
        }
    })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert('Fail');
        });
    });
</script>

Solution1/StarBazar.Web/Views/Product/Details.cshtml
@model StarBazar.Web.ViewModels.ProductViewModel

@if (Model != null && Model.Product != null)
{
    var defaultImageURL = "/Content/images/placeholder-image.png";

    var imageURL = string.IsNullOrEmpty(Model.Product.ImageURL) ? defaultImageURL : Model.Product.ImageURL;

<div class="page-title parallax parallax1">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-title-heading">
                    <h1 class="title">
                        @Model.Product.Name
                    </h1>
                </div><!-- /.page-title-heading -->
            </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</div><!-- /.page-title -->

<section class="flat-row main-shop shop-detail">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="wrap-flexslider">
                    <div class="inner">
                        <div class="flexslider style-1 has-relative">
                            <ul class="slides">
                                <li data-thumb="@imageURL">
                                    <img src="@imageURL" alt="Image">
                                    <div class="flat-icon style-1">
                                        <a href="@imageURL" class="zoom-popup"><span class="fa fa-search-plus"></span></a>
                                    </div>
                                </li>
                                @*
                                <li data-thumb="images/shop/sh-detail/thumb-detail-02.jpg">
                                    <img src="images/shop/sh-detail/detail-01.jpg" alt="Image">
                                    <div class="flat-icon style-1">
                                        <a href="images/shop/sh-detail/detail-01.jpg" class="zoom-popup"><span class="fa fa-search-plus"></span></a>
                                    </div>
                                </li>
                                <li data-thumb="images/shop/sh-detail/thumb-detail-03.jpg">
                                    <img src="images/shop/sh-detail/detail-01.jpg" alt="Image">
                                    <div class="flat-icon style-1">
                                        <a href="images/shop/sh-detail/detail-01.jpg" class="zoom-popup"><span class="fa fa-search-plus"></span></a>
                                    </div>
                                </li>
                                <li data-thumb="images/shop/sh-detail/thumb-detail-04.jpg">
                                    <img src="images/shop/sh-detail/detail-01.jpg" alt="Image">
                                    <div class="flat-icon style-1">
                                        <a href="images/shop/sh-detail/detail-01.jpg" class="zoom-popup"><span class="fa fa-search-plus"></span></a>
                                    </div>
                                </li>*@
                            </ul>
                        </div><!-- /.flexslider -->
                    </div>
                </div>
            </div><!-- /.col-md-6 -->

            <div class="col-md-6">
                <div class="product-detail">
                    <div class="inner">
                        <div class="content-detail">
                            <h2 class="product-title">
                                @Model.Product.Name
                            </h2>
                            @*<div class="flat-star style-1">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star-half-o"></i>
                                <i class="fa fa-star-half-o"></i>
                                <span>(1)</span>
                            </div>*@
                            <p>
                                @Model.Product.Description
                            </p>
                            <div class="price">
                                <ins>
                                    <span class="amount">
                                        $ @Model.Product.Price
                                    </span>
                                </ins>
                            </div>
                            <div class="product-quantity">
                                <div class="quantity">
                                    <input type="text" value="1" name="quantity-number" class="quantity-number">
                                    <span class="inc quantity-button">+</span>
                                    <span class="dec quantity-button">-</span>
                                </div>
                                <div class="add-to-cart">
                                    <a href="#">ADD TO CART</a>
                                </div>
                                <div class="box-like">
                                    <a href="#" class="like"><i class="fa fa-heart-o"></i></a>
                                </div>
                            </div>
                            <div class="product-categories">
                                <span>Categories: </span><a href="#">@Model.Product.Category.Name</a>
                            </div>
                            <ul class="flat-socials">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div><!-- /.product-detail -->
            </div>
        </div><!-- /.row -->
    </div><!-- /.container -->
</section><!-- /.flat-row -->

<section class="flat-row shop-detail-content">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="flat-tabs style-1 has-border">
                    <div class="inner">
                        <ul class="menu-tab">
                            <li class="active">Reviews</li>
                        </ul>
                        <div class="content-tab">
                            <div class="content-inner">
                                <div class="inner max-width-83 padding-top-33">
                                    <ol class="review-list">
                                        <li class="review">
                                            <div class="thumb">
                                                <img src="images/avatar-1.png" alt="Image">
                                            </div>
                                            <div class="text-wrap">
                                                <div class="review-meta">
                                                    <h5 class="name">Sophia Rosla</h5>
                                                    <div class="flat-star style-1">
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star-half-o"></i>
                                                    </div>
                                                </div>
                                                <div class="review-text">
                                                    <p>I wanted to thank you so much for the rug we have received it really is beautiful and expertly made. I will be recommending you to all our friends.</p>
                                                </div>
                                            </div>
                                        </li><!--  /.review    -->
                                        <li class="review">
                                            <div class="thumb">
                                                <img src="images/avatar.png" alt="Image">
                                            </div>
                                            <div class="text-wrap">
                                                <div class="review-meta">
                                                    <h5 class="name">Jayne Haughton</h5>
                                                    <div class="flat-star style-1">
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star-half-o"></i>
                                                    </div>
                                                </div>
                                                <div class="review-text">
                                                    <p class="line-height-28">Customer service is very important part of the buying experience to us and we must say that we have found Utility's to be impressive - we will certainly look to buy again in future.</p>
                                                </div>
                                            </div>
                                        </li><!--  /.review    -->
                                    </ol><!-- /.review-list -->
                                    <div class="comment-respond review-respond" id="respond">
                                        <div class="comment-reply-title margin-bottom-14">
                                            <h5>Write a review</h5>
                                            <p>Your email address will not be published. Required fields are marked *</p>
                                        </div>
                                        <form novalidate="" class="comment-form review-form" id="commentform" method="post" action="#">
                                            <p class="flat-star style-2">
                                                <label>Rating*:</label>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                            </p>
                                            <p class="comment-form-comment">
                                                <label>Review*</label>
                                                <textarea class="" tabindex="4" name="comment" required> </textarea>
                                            </p>
                                            <p class="comment-name">
                                                <label>Name*</label>
                                                <input type="text" aria-required="true" size="30" value="" name="name" id="name">
                                            </p>
                                            <p class="comment-email">
                                                <label>Email*</label>
                                                <input type="email" size="30" value="" name="email" id="email">
                                            </p>
                                            <p class="comment-form-notify clearfix">
                                                <input type="checkbox" name="check-notify" id="check-notify"> <label for="check-notify">Notify me of new posts by email</label>
                                            </p>
                                            <p class="form-submit">
                                                <button class="comment-submit">Submit</button>
                                            </p>
                                        </form>
                                    </div><!-- /.comment-respond -->
                                </div>
                            </div><!-- /.content-inner -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section><!-- /.shop-detail-content -->

<section class="flat-row shop-related">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section margin-bottom-55">
                    <h2 class="title">Related Products</h2>
                </div>

                @{Html.RenderAction("Products", "Widget", new { isLatestProducts = false, CategoryID = Model.Product.Category.Id });}

            </div>
        </div><!-- /.row -->
    </div>
</section>
                        }

Solution1/StarBazar.Web/Views/Product/Edit.cshtml
@model StarBazar.Web.ViewModels.EditProductViewModel
@{
    ViewBag.Title = "Edit";
    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/images/placeholder-image.png";
}

<h2>Edit Product</h2>

<form id="editContainer">
    <input type="hidden" name="ID" value="@Model.ID" />
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Category</label>
                <select class="form-control" name="CategoryID">
                    @foreach (var category in Model.AvailableCategories)
                    {
                        var selected = category.Id == Model.CategoryID ? "selected" : string.Empty;
                        <option value="@category.Id" @selected>@category.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" name="Name" value="@Model.Name" />
            </div>
            <div class="form-group">
                <label>Description</label>
                <input class="form-control" name="Description" value="@Model.Description" />
            </div>
            <div class="form-group">
                <label>Price</label>
                <input class="form-control" name="Price" value="@Model.Price" />
            </div>
            <div class="form-group">
                <label>Image</label>
                <input type="hidden" id="ImageURL" name="ImageURL" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
            </div>

            <button id="btnEditSave" type="button" class="btn btn-primary">Update</button>
            <button id="cancelBtn" type="button" class="btn btn-primary">Cancel</button>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img class="img-thumbnail img-fluid" id="productImage" src="@imageURL" />
            </div>
        </div>
    </div>
</form>


<script>
    $("#btnEditSave").click(function () {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Edit", "Product")',
            data: $('#editContainer').serialize()
        })
            .done(function (data) {
                $('#tableContainer').html(data);
                $('#actionContainer').html('');
            })

            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert('Fail');
            });

    });

    $("#imageUpload").change(function () {
        var element = this;

        var formData = new FormData();

        var totalFiles = element.files.length;

        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
            .done(function (reposne) {
                console.log(reposne);


                if (reposne.Success) {
                    $("#ImageURL").val(reposne.ImageURL);
                    $("#productImage").attr("src", reposne.ImageURL);
        }
    })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert('Fail');
        });
    });
</script>

Solution1/StarBazar.Web/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<section class="flat-row flat-iconbox">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section">
                    <h2 class="title">
                        Products
                    </h2>
                </div>
            </div>
        </div>

        <div id="tableContainer">
            @{
                Html.RenderAction("ProductTable");

                //Html.RenderAction("Create");
            }
        </div>

        <hr />
        <div id="actionContainer">

        </div>

    </div>
</section>
<script>
    function focusAction(controlToFocus) {
        $('html, body').animate({
            scrollTop: $("#" + controlToFocus).offset().top - 100
        }, 1000);
    }
</script>