Solution1/StarBazar.Web/Controllers/CategoryController.cs
using StarBazar.Entities;
using StarBazar.Services;
using StarBazar.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StarBazar.Web.Controllers
{
    public class CategoryController : Controller
    {
        CategoryService categoryService = new CategoryService();
        // GET: Category

        public ActionResult CategoryTable(string search)
        {
            var categories = categoryService.GetCategories();
            if (string.IsNullOrEmpty(search) == false)
            {
                categories = categories.Where(p => p.Name != null && p.Name.ToLower().Contains(search.ToLower())).ToList();
            }
            return PartialView(categories);
        }

        public ActionResult Index()
        {
            var categoryList = categoryService.GetCategories();
            return View(categoryList);
        }
        public ActionResult Create()
        {
            var categoryList = categoryService.GetCategories();
            return PartialView(categoryList);
        }

        [HttpPost]
        public ActionResult Create(NewCategoryViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var newCategory = new Category();
                newCategory.Name = vm.Name;
                newCategory.Description = vm.Description;
                newCategory.ImageURL = vm.ImageURL;
                newCategory.isFeatured = vm.isFeatured;

                categoryService.SaveCategory(newCategory);

                return RedirectToAction("CategoryTable");
            }
            else
            {
                return new HttpStatusCodeResult(500);
            }
        }

        public ActionResult Edit(int id)
        {
            EditCategoryViewModel model = new EditCategoryViewModel();

            var category = categoryService.GetCategoryById(id);

            model.Id = category.Id;
            model.Name = category.Name;
            model.Description = category.Description;
            model.ImageURL = category.ImageURL;
            model.isFeatured = category.isFeatured;
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(EditCategoryViewModel vm)
        {
            var existingCategory = categoryService.GetCategoryById(vm.Id);
            existingCategory.Name = vm.Name;
            existingCategory.Description = vm.Description;
            existingCategory.ImageURL = vm.ImageURL;
            existingCategory.isFeatured = vm.isFeatured;

            categoryService.UpdateCategory(existingCategory);

            return RedirectToAction("CategoryTable");
        }


        [HttpPost]
        public ActionResult Delete(int Id)
        {
            categoryService.DeleteCategory(Id);
            return RedirectToAction("CategoryTable");
        }
        
    }
}

Solution1/StarBazar.Web/Controllers/UserDetailsController.cs
using StarBazar.Entities;
using StarBazar.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StarBazar.Web.Controllers
{
    public class UserDetailsController : Controller
    {
        // GET: UserDetails
        public ActionResult Index(string search)
        {
            BindState();
            var locations = UserDetailsService.Instance.GetLocations();
            //if (string.IsNullOrEmpty(search) == false)
            //{
            //    locations = locations.Where(p => p.Pincode.ToString() != null).ToList();
            //}
            return View(locations);
            
        }

        public void BindState()
        {
            var state = UserDetailsService.Instance.GetStates();
            List<SelectListItem> li = new List<SelectListItem>();
            li.Add(new SelectListItem { Text = "--Select State--", Value = "0" });

            foreach (var m in state)
            {
                li.Add(new SelectListItem { Text = m.StateName, Value = m.StateId.ToString() });
                ViewBag.state = li;
            }
        }

        public JsonResult GetDistrict(int id)
        {
            var ddlDistrict =UserDetailsService.Instance.GetDistrictByState(id);
            List<SelectListItem> licities = new List<SelectListItem>();

            licities.Add(new SelectListItem { Text = "--Select District--", Value = "0" });
            if (ddlDistrict != null)
            {
                foreach (var x in ddlDistrict)
                {
                    licities.Add(new SelectListItem { Text = x.DistrictName, Value = x.DistrictId.ToString() });
                }
            }
            return Json(new SelectList(licities, "Value", "Text", JsonRequestBehavior.AllowGet));
        }

        
        public JsonResult GetPincode(int id)
        {
            var ddlPincode = UserDetailsService.Instance.GetPincodeByDistrict(id);
            List<SelectListItem> licities = new List<SelectListItem>();

            licities.Add(new SelectListItem { Text = "--Select District--", Value = "0" });
            if (ddlPincode != null)
            {
                foreach (var x in ddlPincode)
                {
                    licities.Add(new SelectListItem { Text = x.Pincode.ToString(), Value = x.PincodetId.ToString() });
                }
            }
            return Json(new SelectList(licities, "Value", "Text", JsonRequestBehavior.AllowGet));
        }
       
    }
}

Solution1/StarBazar.Web/Views/UserDetails/Index.cshtml
@model StarBazar.Entities.UserDetails

@{
    ViewBag.Title = "Index";
}
@using (Html.BeginForm())
{

<section class="flat-row flat-iconbox">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section">
                    <h2 class="title">
                        User Details
                    </h2>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.StateId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.StateId, ViewBag.state as List<SelectListItem>, new { style = "width: 200px;" })

                        @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DistrictId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.DistrictId, new SelectList(string.Empty, "Value", "Text"), "--Select City--", new { style = "width:200px" })

                        @Html.ValidationMessageFor(model => model.DistrictId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PincodetId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.PincodetId, new SelectList(string.Empty, "Value", "Text"), "--Select Pincode--", new { style = "width:200px" })

                        @Html.ValidationMessageFor(model => model.PincodetId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <form method="post" href="@Url.Action("CategoryTable", "Category")">
                    <label>Search</label>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <input id="idSearch" class="form-control" type="search" />
                            </div>
                        </div>
                        <div class="col-md-4">
                            <button type="button" id="btnSearch">Search</button>
                        </div>
                    </div>

                </form>

                <label>District Name</label>
                <input id="txtDistrict" class="form-control" type="text" />

            </div>
        </div>
        <hr />
       

    </div>
</section>

}

<script>
    $(document).ready(function () {

        $("#btnSearch").click(function () {
            debugger;
        var search = $("#idSearch").val();
        $.ajax({
            url:'@Url.Action("Index", "UserDetails")',
            data: {
                search: search
            }

        })
            .done(function (data) {
                $('#EditTableContainer').html(data)
                $('#actionEditContainer').html('')
            })

            .fail(function (xmlHttpRequest, textStatus) {
                alert('Fail');
            });

    });



        $("#StateId").change(function () {
            $("#DistrictId").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetDistrict")',
                dataType: 'json',
                data: { id: $("#StateId").val() },
                success: function (district) {

                    $.each(district, function (i, district) {
                        $("#DistrictId").append('<option value="'
                            + district.Value + '">'
                            + district.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
            return false;
        })


        $("#DistrictId").change(function () {
            $("#PincodetId").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetPincode")',
                dataType: 'json',
                data: { id: $("#DistrictId").val() },
                success: function (pincode) {
                    $.each(pincode, function (i, pincode) {
                        $("#PincodetId").append('<option value="'
                            + pincode.Value + '">'
                            + pincode.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
            return false;
        })

    });
</script>  